# Generated by Django 5.1.5 on 2025-01-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_alter_student_reg_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=64)),
                ('course_name', models.CharField(max_length=64)),
                ('dept_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.department')),
            ],
        ),
    ]
