# Generated by Django 5.1.5 on 2025-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0004_course_semester_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
