# Generated by Django 5.1.5 on 2025-01-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0005_course_credit_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_teaches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ums.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
    ]
