# Generated by Django 5.1.5 on 2025-01-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0006_teacher_course_teaches_alter_course_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='hall',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[(1, 'Lectuerer'), (2, 'Assistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], default=None, max_length=64),
        ),
    ]
