# Generated by Django 5.1.5 on 2025-01-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0007_remove_staff_hall_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[(1, 'Lectuerer'), (2, 'Assistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], default=None, max_length=64, null=True),
        ),
    ]
